name: CD

on:
  push:
    branches: ['master']

jobs:
  docsify:
    name: docsify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2
        with:
          username: '${{ secrets.SFTP_USERNAME }}'
          server: '${{ secrets.SFTP_SERVER }}'
          port: '${{ secrets.SFTP_PORT }}'
          ssh_private_key: ${{ secrets.SFTP_PRIVKEY }} 
          local_path: './docs/*'
          remote_path: '/var/www/wiki.banablock.net'
          args: '-o ConnectTimeout=5'
